### ISSUE TITLE
Constrained attvars should constrain attributes (in case SWI changes this)

### ISSUE THREAD

**Issue by TeamSPoon** [logicmoo/fluentvars#3]
UWN:

> While the incorrectness issue is gone, dif/2 is still very weak (compared to other implementations):
> 
> ```
> ?- dif(X-Y, 1-2), X = Y.
> X = Y,
> dif(f(Y, Y), f(1, 2)).
> ```
> 
> Expected: Only X = Y.

Dmiles

> X=Y, but X and Y must never be 1 or 2 so at least some attributes must remain

**Comment by triska** [comment]
> X=Y, but X and Y must never be 1 or 2 so at least some attributes must remain

That's not the case. Suppose X and Y are both 1, then the constraint still holds: `dif(1-1, 1-2)`. Likewise, it holds if both are&nbsp;2. In fact, the most recent SWI versions behaves exactly as Ulrich expected:

<pre>
?- dif(X-Y, 1-2), X = Y.
X = Y.
</pre>

This answer is **correct**.

**Comment by TeamSPoon** [comment]
Aha, I see now.
thank you @triska
